

(function () {
    var baseUrl = Lizard.appBaseUrl + 'res/';

    require.config({
        paths: {
            'Stack':                        baseUrl + 'util/stack',
            'PageManager':                  baseUrl + 'comm/pagemanager',
            'Scmg':                         baseUrl + 'comm/scmg',
            'WalletModel':                  baseUrl + 'models/walletmodel',
            'WalletStore':                  baseUrl + 'models/walletstore',
            'WalletSession':                  baseUrl + 'models/walletsession',
            'Log':                          baseUrl + 'util/log',
            'Util':                         baseUrl + 'util/util',
            'IdCard':                       baseUrl + 'util/idcard',
            "UBT":                          baseUrl + 'util/ubt',
            'Message':                      baseUrl + 'comm/message',
            'Config':                       baseUrl + 'config/config',
            'FeedModel':                    baseUrl + 'models/feedmodel',
            'WalletBaseModel':              baseUrl + 'models/walletbasemodel',
            'CacheData':                    baseUrl + 'models/cachedata',
            'MockModel':                    baseUrl + 'models/mockmodel',
            'ModelObserver':                baseUrl + 'models/modelobserver',
            'IdCodePageView':               baseUrl + 'baseview/idcodepageview',
            'WalletPageView':               baseUrl + 'baseview/walletpageview',
            'CustomMessage':                baseUrl + 'widget/custommessage',
            'VirtualKeyBoard':              baseUrl + 'widget/virtualkeyboard',
            'CerKeyBoard':                  baseUrl+'widget/cerkeyboard',
            'GetCerList':                   baseUrl+'widget/getcerlist',
            'WxShare':                      baseUrl+'widget/wxshare',
            'CheckPsd':                      baseUrl+'widget/checkpsd',
            'WalletListView':               baseUrl + 'baseview/walletlistpageview',
            'WalletSelectCtrl':             baseUrl + 'widget/walletselectctrl',
            'LoadingLayer':                 baseUrl + 'widget/loading',
            'WalletLoading':                baseUrl+'widget/walletloading',
            'WalletInputView':              baseUrl + 'baseview/walletinputpageview',
            'WalletFilterListView':         baseUrl + 'baseview/walletfilterlistpageview',
            "Tradelist":                    baseUrl + 'widget/tradelist',
            "WalletResk":                   baseUrl + 'widget/reskassess',
            'BalConfig':                    baseUrl + 'config/balconfig',//balance config
            'VerfiedpsdFloat':              baseUrl + 'widget/verfiedpsdfloat',
            'FingerHelper':                 baseUrl + 'comm/fingerhelper',
            'PopupSelect':                  baseUrl + 'widget/popupselect',
            'PayVerify':                    baseUrl + 'widget/payverify',
            "WalletCardInfo":               baseUrl + "baseview/walletcardinfo",
            "WalletBindCardService":        baseUrl + "baseview/walletbindcardservice",
            "RealName":                     baseUrl + "widget/realname",
            "VerifySelect":                 baseUrl + "widget/verifyselect",
            "BirthChoicer":                 baseUrl + "widget/birthchoicer",
            "PageMap":                      baseUrl + "comm/pagemap",
            "WalletBasePlugin":             baseUrl + "plugin/WalletBasePlugin",
            "IndexPlugin":                  baseUrl + "plugin/IndexPlugin",
            "AdPlugin":                     baseUrl + "plugin/AdPlugin",

            "404warning_html":              baseUrl + "tpl/404warning.html",
            "addcard_html":                 baseUrl + "tpl/addcard.html",
            "authstatus_html":              baseUrl + "tpl/authstatus.html",
            "debug_html":                   baseUrl + "tpl/debug.html",
            "debug2_html":                  baseUrl + "tpl/debug2.html",
            "index_html":                   baseUrl + "tpl/index.html",
            "inputmoney_html":              baseUrl + "tpl/inputmoney.html",
            "modifysecuritymobile_html":    baseUrl + "tpl/modifysecuritymobile.html",
            "modifysecuritymobile2_html":   baseUrl + "tpl/modifysecuritymobile2.html",
            "mybankcard_html":              baseUrl + "tpl/mybankcard.html",
            "rechargedetail_html":          baseUrl + "tpl/rechargedetail.html",
            "rechargelist_html":            baseUrl + "tpl/rechargelist.html",
            "resetpaypsd_html":             baseUrl + "tpl/resetpaypsd.html",
            "result_html":                  baseUrl + "tpl/result.html",
            "securitycenter_html":          baseUrl + "tpl/securitycenter.html",
            "selectctrl_html":              baseUrl + "tpl/selectctrl.html",
            "selectpage_html":              baseUrl + "tpl/selectpage.html",
            "setpaypsd_html":               baseUrl + "tpl/setpaypsd.html",
            "setpaypsd2_html":              baseUrl + "tpl/setpaypsd2.html",
            "setsecuritymobile_html":       baseUrl + "tpl/setsecuritymobile.html",
            "switchcash_html":              baseUrl + "tpl/switchcash.html",
            "transactdetail_html":          baseUrl + "tpl/transactdetail.html",
            "transacthistory_html":         baseUrl + "tpl/transacthistory.html",
            "tranxlist_html":               baseUrl + "tpl/tranxlist.html",
            "verfiedpsd_html":              baseUrl + "tpl/verfiedpsd.html",
            "withdraw_html":                baseUrl + "tpl/withdraw.html",
            "withdrawbackconfirm_html":     baseUrl + "tpl/withdrawbackconfirm.html",
            "withdrawdetail_html":          baseUrl + "tpl/withdrawdetail.html",
            "withdrawlist_html":            baseUrl + "tpl/withdrawlist.html",

            "cancelfinger_html":            baseUrl + "tpl/cancelfinger.html",
            "howtosetfingerandroid_html":   baseUrl + "tpl/howtosetfingerandroid.html",
            "howtosetfingerios_html":       baseUrl + "tpl/howtosetfingerios.html",
            "enablefinger_html":            baseUrl + "tpl/enablefinger.html",
            "obligation_html":              baseUrl + "tpl/obligation.html",
            "popupselect_html":             baseUrl + "tpl/popupselect.html",

            "addpostcity_html":             baseUrl + "tpl/balance/addpostcity.html",
            "addpostprovince_html":         baseUrl + "tpl/balance/addpostprovince.html",
            "autotogift_html":              baseUrl + "tpl/balance/autotogift.html",
            "cashcouponlist_html":          baseUrl + "tpl/balance/cashcouponlist.html",
            "manualtogift_html":            baseUrl + "tpl/balance/manualtogift.html",
            "payoutlist_html":              baseUrl + "tpl/balance/payoutlist.html",
            "selbankcard_html":             baseUrl + "tpl/balance/selbankcard.html",
            "todebitcard_html":             baseUrl + "tpl/balance/todebitcard.html",
            "transferid_html":              baseUrl + "tpl/balance/transferid.html",
            "useraccount_html":             baseUrl + "tpl/balance/useraccount.html",
            "transfertocardno_html":        baseUrl + "tpl/balance/transfertocardno.html",
            "transfertocard_html":          baseUrl + "tpl/balance/transfertocard.html",
            "phonevalidate_html":           baseUrl + "tpl/balance/phonevalidate.html",
            "exchgphone_html":              baseUrl + "tpl/balance/exchgphone.html",
            "rechargephone_html":           baseUrl + "tpl/balance/rechargephone.html",

            "setpaypassword_html":          baseUrl + "tpl/setpaypassword.html",
            "fastpay_html":                 baseUrl + "tpl/fastpay.html",
            "fastpaysetting_html":          baseUrl + "tpl/fastpaysetting.html",
            "fastpayconfirm_html":          baseUrl + "tpl/fastpayconfirm.html",

            "walletcardinfo_html":          baseUrl + "tpl/walletcardinfo.html",
            "validatepremobile_html":       baseUrl + "tpl/validatepremobile.html",
            "cardidentifying_html":         baseUrl + "tpl/cardidentifying.html",
            "cardvalidity_html":            baseUrl + "tpl/cardvalidity.html",
            "realname_html":                baseUrl + "tpl/realname.html",
            "supportbanks_html":            baseUrl + "tpl/supportbanks.html",
            "accountverified_html":         baseUrl + "tpl/accountverified.html",
            "insrcactivity_html":           baseUrl + "tpl/insrcactivity.html",
            "myinsrc_html":                 baseUrl + "tpl/myinsrc.html",
            "myinsrcdetail_html":           baseUrl + "tpl/myinsrcdetail.html",
            "myinsrcclaim_html":            baseUrl + "tpl/myinsrcclaim.html",
            "insrcaddinfo_html":            baseUrl + "tpl/insrcaddinfo.html",
            "insrcend_html":                baseUrl + "tpl/insrcend.html",
            "insrctips_html":               baseUrl + "tpl/insrctips.html",
            "insrcstart_html":              baseUrl + "tpl/insrcstart.html",
            "readme_html":                  baseUrl + "tpl/readme.html"
        }
    });
})();